# SonarQube/SonarCloud Configuration File
sonar.organization=uo294431
sonar.host.url=https://sonarcloud.io
sonar.projectKey=UO294431_EPI-DevorApp
sonar.projectName=EPI-DevorApp
sonar.projectVersion=1.0

# Source and Test directories
sonar.sources=backend/app,frontend/src,keras-api/main.py,keras-api/train_pipeline.py
sonar.tests=backend/tests,frontend/src/tests,keras-api/test_main.py

# Exclusions
sonar.exclusions=**/node_modules/**,**/android/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts,frontend/src/tests/**

# Exclude entrypoints, APIs, DTOs, repositories and views from coverage
sonar.coverage.exclusions=keras-api/train_pipeline.py,frontend/src/views/**,frontend/src/App.tsx,frontend/src/main.tsx,frontend/src/models/api/**,backend/app/models/dtos/**,backend/app/infrastructure/repositories/**,backend/app/presentation/router_utils.py

# Exclude views/pages from Copy-Paste Detection (CPD) duplication analysis
sonar.cpd.exclusions=frontend/src/views/**,backend/app/models/dtos/**

# Coverage Reports
sonar.python.coverage.reportPaths=backend/coverage.xml,keras-api/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Disable JS/TS Jasmin sensor V2 due to hanging issue
sonar.jasmin.internal.disabled=true

# Encoding
sonar.sourceEncoding=UTF-8

